import type { Metadata } from "next";

import "./globals.css";
import classes from "./page.module.css"
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "My SPA Application",
  description: "Generated by create next js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={classes.container}>
        <Header />
        {children}
      </body>
    </html>
  );
}
